data_dir: /path/to/datadir
satellite_default:
  resolution: 30
  tile_size: 5_000
  composite_method: "MEDIAN" # see geefetch.enums.CompositeMethod
  dtype: UInt16
  aoi:
    spatial:
      left: 124
      right: 131
      top: 43
      bottom: 34
      epsg: 4326
    temporal:
      start_date: "2021-01-01"
      end_date: "2021-12-31"
  gee:
    ee_project_id: "ee-project-i"
    max_tile_size: 8 # in MB, decrease if User Memory Excess Error, choose highest possible otherwise.

landsat8: {}
